### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by alexandre-perrin** [raspberrypi/picamera2#1164]
**Describe the bug**

Running [imx500_object_detection_demo.py](https://github.com/raspberrypi/picamera2/blob/main/examples/imx500/imx500_object_detection_demo.py) on Raspberry Pi 5 with IMX500 camera with `--postprocess nanodet` fails with: `ValueError: operands could not be broadcast together with shapes (1,0,4) (1,3598,1)`

**To Reproduce**

On Raspberry Pi 5 with AI Camera:
execute the demo script with `--postprocess nanodet` option:

```
python imx500_object_detection_demo.py --postprocess nanodet
```

**Expected behaviour**

Camera starts and application keeps running without crash.

**Console Output, Screenshots**

```
Traceback (most recent call last):
  File "/home/alexandre/aitrios-sdk-edge-app-dev/sample_apps/detection/python/imx500_object_detection_demo.py", line 246, in <module>
    last_results = parse_detections(picam2.capture_metadata())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/aitrios-sdk-edge-app-dev/sample_apps/detection/python/imx500_object_detection_demo.py", line 40, in parse_detections
    boxes, scores, classes = postprocess_nanodet_detection(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/picamera2/devices/imx500/postprocess_nanodet.py", line 38, in postprocess_nanodet_detection
    distances = x * anchors[..., 2, None]
                ~~^~~~~~~~~~~~~~~~~~~~~~~
ValueError: operands could not be broadcast together with shapes (1,0,4) (1,3598,1)
```

**Hardware :**

Raspberry Pi 5 with AI Camera IMX500

**Additional context**

**Comment by v4m3rrr** [comment]
Same on Raspberry Pi 4.
