### ISSUE TITLE
[BUG] Requested camera dev-node not found

### ISSUE THREAD

**Issue by JadeKim042386** [raspberrypi/picamera2#1180]
**Please only report one bug per issue!**

**Describe the bug**

i tried this
```
~/Desktop/picamera2/examples/imx500 $ python imx500_object_detection_demo.py
```
and 
```
RuntimeError: IMX500: Requested camera dev-node not found
```

**To Reproduce**

after installed os, i installed it in the following order
```
sudo apt update && sudo apt full-upgrade
sudo apt install imx500-full
sudo apt install python3-opencv python3-munkres
sudo apt install python3-picamera2
```

and i cloned git repository
```
git clone https://github.com/raspberrypi/picamera2.git
```

and ran imx500_object_detection_demo.py

**Expected behaviour**
`rpicam-hello -t 0s` is worked
but demo script is not working... i expected camera screen...

**Console Output, Screenshots**
```
Traceback (most recent call last):
  File "/home/juyoung/Desktop/picamera2/examples/imx500/imx500_object_detection_demo.py", line 140, in <module>
    imx500 = IMX500(args.model)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/picamera2/devices/imx500/imx500.py", line 312, in __init__
    raise RuntimeError('IMX500: Requested camera dev-node not found')
RuntimeError: IMX500: Requested camera dev-node not found
```

**Hardware :**
```
juyoung@joo-pi5:~/Desktop/picamera2/examples/imx500 $ rpicam-hello --list-cameras
Available cameras
-----------------
0 : ov5647 [2592x1944 10-bit GBRG] (/base/axi/pcie@120000/rp1/i2c@80000/ov5647@36)
    Modes: 'SGBRG10_CSI2P' : 640x480 [58.92 fps - (16, 0)/2560x1920 crop]
                             1296x972 [46.34 fps - (0, 0)/2592x1944 crop]
                             1920x1080 [32.81 fps - (348, 434)/1928x1080 crop]
                             2592x1944 [15.63 fps - (0, 0)/2592x1944 crop]
```

**Comment by davidplowman** [comment]
Hi, thanks for the question. According to the hardware description you posted, you've got an OV5647 camera - is that correct? The OV5647 is not an IMX500 AI camera and therefore won't work in these examples. Do you perhaps have an IMX500 camera that is not being recognised?
