### ISSUE TITLE
[OTHER] RuntimeError: Camera did not start properly

### ISSUE THREAD

**Issue by Beleggrodion** [raspberrypi/picamera2#199]
I don't know if this exactly a bug or the issue is on other libraries or an hardware issue.

For a small project the following:
- Raspberry Pi 4B 4 GB RAM
- Raspberry Pi 7" Touchscreen
- Raspberry Pi Camera Modul 2 

Together in a SmartiPi Touch Pro Case.

I installed the current bullseye image
```
uname -a
Linux bux-cam 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux
```

I'm not very familiar with python but tried as good as i can to create a small q5 program which open a screen with a preview image , a debug log and the possiblility to show me a countdown in a text label on request.  The program is connected to a simple websocket server which send and receive commands from a website and hande them to the python script.

But currently the capture of a image is very unstable sometimes it works and sometimes the complete script crashes.

```
[5:21:32.435299162] [9332]  INFO Camera camera_manager.cpp:293 libcamera v0.0.0+3544-22656360
[5:21:32.472846546] [9339]  WARN RPI raspberrypi.cpp:1241 Mismatch between Unicam and CamHelper for embedded data usage!
[5:21:32.474469846] [9339]  INFO RPI raspberrypi.cpp:1356 Registered camera /base/soc/i2c0mux/i2c@1/imx219@10 to Unicam device /dev/media2 and ISP device /dev/media0
[5:21:33.478605150] [9332]  INFO Camera camera.cpp:1029 configuring streams: (0) 800x600-XBGR8888
[5:21:33.479005850] [9339]  INFO RPI raspberrypi.cpp:760 Sensor: /base/soc/i2c0mux/i2c@1/imx219@10 - Selected sensor format: 1640x1232-SRGGB10_1X10 - Selected unicam format: 1640x1232-pRAA
[5:22:21.397063487] [9339] ERROR V4L2 v4l2_videodevice.cpp:1852 /dev/video0[21:cap]: Failed to start streaming: Input/output error
2022-07-05T14:13:07.808Z | ERROR    | Camera did not start properly.
Traceback (most recent call last):
  File "/home/support/pi/bux.py", line 148, in on_message
    self.picam2.start()
  File "/home/support/.local/lib/python3.9/site-packages/picamera2/picamera2.py", line 591, in start
    self.start_()
  File "/home/support/.local/lib/python3.9/site-packages/picamera2/picamera2.py", line 572, in start_
    raise RuntimeError("Camera did not start properly.")
RuntimeError: Camera did not start properly.
Aborted
```

Perhaps the warning above is one of the issues which leading to them. But i don't know. I also added some time.sleep(1) in the code, because in the draft pdf of the documentation i see some sleep's to. 

Sometimes it directly crashes when i use

`self.picam2.start()`

sometimes this works and then it crashes on:

```
    self.picam2.switch_mode_and_capture_file(
        self.capture_config,
        "current.jpg",
        wait=False,
        signal_function=self.qpicamera2.signal_done
    )
```

Also dmesg show something like:

```
[19341.581164] imx219 10-0010: Failed to write reg 0x030d. error = -5
[19341.581185] imx219 10-0010: imx219_start_streaming failed to set mode
[19341.581268] unicam fe801000.csi: stream on failed in subdev

```

**Comment by davidplowman** [comment]
Hi, this is almost certainly related to the touchscreen and is a general issue not related to Picamera2 (and not something we can fix in Picamera2). Could you perhaps post a question on the camera forum, I think someone there will be able to help? Thanks!

**Comment by hav4ik** [comment]
I'm having the same issue. No touchscreen. Just connecting over SSH and trying this simplest code:

```python
from picamera2 import PiCamera2
cam = PiCamera2()
cam.start()
cam.capture_file('test.png')
```

```
