### ISSUE TITLE
no module named pykms

### ISSUE THREAD

**Issue by pbaetens** [raspberrypi/picamera2#275]
raspberry pi4 with 64 bit image installed with latest sw.
I compiled libcamera and libcamera-apps from source with python bindings enabled. Those work fine.
I had many issues installing picamera2 (complaining about pyqt5) while it was installed using sudo-apt - it still tried to install with pip...
Then I change to branch `next`
install from source using `pip3 install .`
during import kms seems missing - but I cant find a way to install pykms.

```
pi@raspberrypi:~/picamera2 $ python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import picamera2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/picamera2/picamera2/__init__.py", line 5, in <module>
    from .picamera2 import Picamera2, Preview
  File "/home/pi/picamera2/picamera2/picamera2.py", line 22, in <module>
    from picamera2.previews import DrmPreview, NullPreview, QtGlPreview, QtPreview
  File "/home/pi/picamera2/picamera2/previews/__init__.py", line 1, in <module>
    from .drm_preview import DrmPreview
  File "/home/pi/picamera2/picamera2/previews/drm_preview.py", line 6, in <module>
    import pykms
ModuleNotFoundError: No module named 'pykms'
```

**Comment by pbaetens** [comment]
update: installing pykmsxx from git solves the issue. [kmsxx](https://github.com/tomba/kmsxx/)
not sure if this is the normal way.

**Comment by pbaetens** [comment]
also had to change the python requirement in setup.py to 3.7 since this is what comes with raspberry pi os.

**Comment by pbaetens** [comment]
probably because I was on buster and not bullseye.
