### ISSUE TITLE
[BUG] TypeError: unsupported operand type(s) for |: 'dict' and 'dict'

### ISSUE THREAD

**Issue by pbaetens** [raspberrypi/picamera2#276]
`pi@raspberrypi:~/picamera2 $ python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycamera2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pycamera2'
>>> import picamera2
>>> picamera.Picamera()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'picamera' is not defined
>>> picamera2.Picamera2()
[46:58:42.368470766] [6483]  INFO Camera camera_manager.cpp:293 libcamera v0.0.0+3751-22ffeae0-dirty (2022-08-19T00:26:43-09:00)
[46:58:42.621557693] [6487]  WARN RPI raspberrypi.cpp:1252 Mismatch between Unicam and CamHelper for embedded data usage!
[46:58:42.623974276] [6487]  INFO RPI raspberrypi.cpp:1368 Registered camera /base/soc/i2c0mux/i2c@1/mira050@36 to Unicam device /dev/media3 and ISP device /dev/media2
2022-08-19T11:39:29.737Z | ERROR    | Camera __init__ sequence did not complete.
Traceback (most recent call last):
  File "/home/pi/picamera2/picamera2/picamera2.py", line 125, in __init__
    self.preview_configuration = self.create_preview_configuration()
  File "/home/pi/picamera2/picamera2/picamera2.py", line 470, in create_preview_configuration
    "FrameDurationLimits": (100, 83333)} | controls
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/picamera2/picamera2/picamera2.py", line 130, in __init__
    raise RuntimeError("Camera __init__ sequence did not complete.")
RuntimeError: Camera __init__ sequence did not complete.
>>> exit()`

**Comment by pbaetens** [comment]
probably because I was on buster and not bullseye.
