### ISSUE TITLE
[HOW-TO] Release camera

### ISSUE THREAD

**Issue by arseniymerkulov** [raspberrypi/picamera2#306]
After executing following code on raspberry pi 4 i get this error on second capture. It seems like before creating new Picamera, old one needs to be released. How can i do it? 
```
from picamera2 import Picamera2
import time

def capture(image_path):
    camera = Picamera2()
    capture_config = camera.create_still_configuration()
    camera.configure(capture_config)
    camera.start()

    time.sleep(1)
    camera.switch_mode_and_capture_file(capture_config, image_path)

capture('t1.jpg')
capture('t2.jpg')
```

```[3:36:19.335474988] [12149] ERROR Camera camera.cpp:533 Camera in Running state trying acquire() requiring state Available
2022-09-08T11:41:08.214Z | ERROR    | Camera __init__ sequence did not complete.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 123, in __init__
    self._open_camera()
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 310, in _open_camera
    raise RuntimeError("Failed to acquire camera")
RuntimeError: Failed to acquire camera

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/pythoncamera/test.py", line 14, in <module>
    capture('t2.jpg')
  File "/home/pi/pythoncamera/test.py", line 5, in capture
    camera = Picamera2()
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 130, in __init__
    raise RuntimeError("Camera __init__ sequence did not complete.")
RuntimeError: Camera __init__ sequence did not complete.
```

**Comment by chrisruk** [comment]
The following did the trick for me -

```
camera.close()
```

**Comment by arseniymerkulov** [comment]
thanks
