### ISSUE TITLE
[HOW-TO]: Take multiple .dng images

### ISSUE THREAD

**Issue by Scottyy-M** [raspberrypi/picamera2#318]
Hi, I am trying to make a program to take a photo on command. I have it working with .jpeg's however would like to take .dng's. The first image is captured successfully, however, I am currently struggling with being able to take a 2nd image. I am using a RPi4B with the NoIR RPi camera v2.

**To Reproduce**
Firstly I have tried following the example "capture_dng_and_jpeg.py" with my program below:
```
import time
import os
import datetime
import traceback
from picamera2 import Picamera2

count = 0

picam2 = Picamera2()
picam2.start()
capture_config = picam2.create_still_configuration(raw={})

folder_picam2 = "/home/pi/Pictures/picam2"
if not os.path.exists(folder_picam2):
	os.makedirs(folder_picam2)

try:
	while True:
		input("Press ENTER to take a photo")
		count += 1

		filename_picam2_jpeg = str(datetime.datetime.now().strftime("%H%M%S")) + "_" + "picam2" + "_" + str(count) + ".jpeg"
		filename_picam2_dng = str(datetime.datetime.now().strftime("%H%M%S")) + "_" + "picam2" + "_" + str(count) + ".dng"

		r = picam2.switch_mode_capture_request_and_stop(capture_config)
		r.save("main", folder_picam2 + "/" + filename_picam2_jpeg)
		r.save_dng(folder_picam2 + "/" + filename_picam2_dng)
		
		print("{} photos taken".format(count))
		
except KeyboardInterrupt:
	print("Keyboard Int")
	
except Exception as e:
	print(traceback.format_exc())

finally:
	picam2.close()
	print("Disconnected from cameras")
	time.sleep(2)
```
In the above program the first photo is ok, however the 2nd photo hangs indefinitely.
I added the following try except in an attempt to start the camera again after the function "switch_mode_capture_request_and_stop()" appears to stop the camera?
```
try:
	picam2.start()
except RuntimeError:
	pass
```
However, this returns the following error upon taking the 2nd image:

> Traceback (most recent call last):
>   File "/home/pi/take_photos.py", line 30, in <module>
>     r = picam2.switch_mode_capture_request_and_stop(capture_config)
>   File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 1109, in switch_mode_capture_request_and_stop
>     return self.wait()
>   File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 995, in wait
>     result = self._future.result()
>   File "/usr/lib/python3.9/concurrent/futures/_base.py", line 440, in result
>     return self.__get_result()
>   File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
>     raise self._exception
>   File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 958, in process_requests
>     done, result = function()
>   File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 1052, in switch_mode_
>     self.configure_(camera_config)
>   File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 813, in configure_
>     self.video_configuration.update(camera_config)
>   File "/usr/lib/python3/dist-packages/picamera2/configuration.py", line 55, in update
>     self.__setattr__(k, v)
>   File "/usr/lib/python3/dist-packages/picamera2/configuration.py", line 39, in __setattr__
>     value = self._FIELD_CLASS_MAP[name](value)
>   File "/usr/lib/python3/dist-packages/picamera2/configuration.py", line 31, in __init__
>     self.__setattr__(k, v)
>   File "/usr/lib/python3/dist-packages/picamera2/configuration.py", line 42, in __setattr__
>     raise RuntimeError(f"Invalid field '{name}'")
> RuntimeError: Invalid field 'bpp'

I have no idea what "bpp" is?
I tried swapping the capture image lines for the "capture_dng.py" example too with the function:
`picam2.switch_mode_and_capture_file(capture_config, filename_picam2_dng, name="raw")`
This worked for the first image, but on the 2nd image I get the same error as before.

I also tried the example "capture_dng_and_jpeg_helpers.py" which returns the same error. 

Thank you in advance

**Comment by Scottyy-M** [comment]
Thanks @davidplowman, I'll give that a go and let you know if I have any further questions!
