### ISSUE TITLE
[BUG] RPi Bullseye h264_encoder error

### ISSUE THREAD

**Issue by sam1177** [raspberrypi/picamera2#380]
>>> from picamera2.encoders import H264Encoder, Quality
>>> encoder = H264Encoder()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/picamera2/encoders/h264_encoder.py", line 24, in __init__
    super().__init__(bitrate, V4L2_PIX_FMT_H264)
NameError: name 'V4L2_PIX_FMT_H264' is not defined

Am i missing something?

**Comment by sam1177** [comment]
Upgrading V4L2 fixed the issue
