### ISSUE TITLE
[BUG] RuntimeError: Control NoiseReductionMode is not advertied by libcamera

### ISSUE THREAD

**Issue by GeneiusK** [raspberrypi/picamera2#382]
**Describe the bug**
After updating to arducam's newest update for their libcamera branches, camera no longer initializes 

**To Reproduce**
```
from picamera2 import Picamera2
picam2 = Picamera2()
picam2.camera_controls
```

**Expected behaviour**
initialize camera

**Console Output, Screenshots**
```
[1:06:46.672631007] [19020]  INFO Camera camera_manager.cpp:293 libcamera v0.0.1+21-7c855784
[1:06:46.693898472] [19023]  WARN CameraSensorProperties camera_sensor_properties.cpp:174 No static properties available for 'imx519'
[1:06:46.694040875] [19023]  WARN CameraSensorProperties camera_sensor_properties.cpp:176 Please consider updating the camera sensor properties database
[1:06:46.799614628] [19023] ERROR IPADataSerializer raspberrypi_ipa_serializer.h:130 Failed to deserialize sensorMetadata: not enough data, expected 4, got 0
[1:06:46.799738884] [19023] ERROR Serializer control_serializer.cpp:509 Bad data, entry offset mismatch (entry 1)
[1:06:46.799773439] [19023]  WARN RPI raspberrypi.cpp:1297 Mismatch between Unicam and CamHelper for embedded data usage!
[1:06:46.800986906] [19023]  INFO RPI raspberrypi.cpp:1414 Registered camera /base/soc/i2c0mux/i2c@1/imx519@1a to Unicam device /dev/media2 and ISP device /dev/media0
Camera __init__ sequence did not complete.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 161, in __init__
    self.preview_configuration = self.create_preview_configuration()
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 203, in preview_configuration
    self.preview_configuration_ = CameraConfiguration(value, self)
  File "/usr/lib/python3/dist-packages/picamera2/configuration.py", line 94, in __init__
    d = {k: v if k != "controls" else Controls(picam2, v) for k, v in d.items()}
  File "/usr/lib/python3/dist-packages/picamera2/configuration.py", line 94, in <dictcomp>
    d = {k: v if k != "controls" else Controls(picam2, v) for k, v in d.items()}
  File "/usr/lib/python3/dist-packages/picamera2/controls.py", line 24, in __init__
    self.set_controls(controls)
  File "/usr/lib/python3/dist-packages/picamera2/controls.py", line 58, in set_controls
    self.__setattr__(k, v)
  File "/usr/lib/python3/dist-packages/picamera2/controls.py", line 33, in __setattr__
    raise RuntimeError(f"Control {name} is not advertied by libcamera")
RuntimeError: Control NoiseReductionMode is not advertied by libcamera

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Desktop/test.py", line 2, in <module>
    picam2 = Picamera2()
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 166, in __init__
    raise RuntimeError("Camera __init__ sequence did not complete.")
RuntimeError: Camera __init__ sequence did not complete.
```

**Hardware :**
raspberry pi 4b, arducam 16mp autofocus

**Additional context**
arducam libcamera branches - 
```
wget -O install_pivariety_pkgs.sh https://github.com/ArduCAM/Arducam-Pivariety-V4L2-Driver/releases/download/install_script/install_pivariety_pkgs.sh
chmod +x install_pivariety_pkgs.sh
./install_pivariety_pkgs.sh -p libcamera_dev
./install_pivariety_pkgs.sh -p libcamera_apps
```

**Comment by davidplowman** [comment]
Hi, I'm afraid it's difficult to help with Arducam's version of libcamera because we don't know what's in them or whether they're up-to-date with the rest of Picamera2.

I would recommend starting with a fresh installation of the latest Raspberry Pi OS image. Check the camera works (you will need `dtoverlay=imx519` in your /boot/config.txt if you're using that camera). Then you will need to install Arducam's software to support their autofocus mechanism - if it that point it no longer works then you should probably contact their support team. Thanks!
