### ISSUE TITLE
mjpeg_server.py not working on Raspberry PI OS Bullseye 64bit

### ISSUE THREAD

**Issue by sajmons** [raspberrypi/picamera2#442]
On fresh instalation of Raspbery Pi OS Bullseye after upgrading and installing picamera2, when I execute this:

`python3 mjpeg_server.py`

I get this

```
[0:18:04.734904960] [8151]  INFO Camera camera_manager.cpp:299 libcamera v0.0.1
[0:18:04.785617146] [8152]  INFO RPI raspberrypi.cpp:1386 Registered camera /base/soc/i2c0mux/i2c@1/imx477@1a to Unicam device /dev/media1 and ISP device /dev/media0
Camera __init__ sequence did not complete.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 239, in __init__
    self._open_camera()
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 450, in _open_camera
    if self._initialize_camera():
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 431, in _initialize_camera
    self.sensor_format = str(self.camera.generate_configuration([RAW]).at(0).pixel_format)
RuntimeError: Non-owning holder (loaded_as_shared_ptr).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stellarmate/Downloads/mjpeg_server.py", line 86, in <module>
    picam2 = Picamera2()
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 246, in __init__
    raise RuntimeError("Camera __init__ sequence did not complete.")
RuntimeError: Camera __init__ sequence did not complete.
```

OS Info:

`Linux stellarmate 5.15.61-v8+ #1579 SMP PREEMPT Fri Aug 26 11:16:44 BST 2022 aarch64 GNU/Linux`

**Comment by davidplowman** [comment]
Hi, I tried this with our latest 64-bit image, let it perform all the updates on first boot, and it seems to work for me. My image reports:
```
Linux raspberrypi 5.15.76-v8+ #1597 SMP PREEMPT Fri Nov 4 12:16:41 GMT 2022 aarch64 GNU/Linux
```
I wonder if you perhaps if you have updated Picamera2 but not its dependencies? Maybe try `sudo apt install -y libcamera0 python3-libcamera` and see if that helps.

**Comment by sajmons** [comment]
I'll be using other solution, so I'm closing this

**Comment by programORdie2** [comment]
Hi! I've the same problem, can you please tell me how you fixed it?
