### ISSUE TITLE
[OTHER]Picamera2 Issue

### ISSUE THREAD

**Issue by Msmhgn** [raspberrypi/picamera2#587]
Hi,

When I ran the raw.py example in RPI, I get this error:
@python raw.py
[0:09:27.408477190] [1997]  INFO Camera camera_manager.cpp:299 libcamera v0.0.0+4186-d1dc0373
[0:09:27.410801406] [1998] ERROR V4L2 v4l2_device.cpp:352 'imx477 10-001a': Unable to set controls: Device or resource busy
[0:09:27.430604169] [1998]  WARN RPI raspberrypi.cpp:1308 Mismatch between Unicam and CamHelper for embedded data usage!
[0:09:27.431468700] [1998]  INFO RPI raspberrypi.cpp:1425 Registered camera /base/soc/i2c0mux/i2c@1/imx477@1a to Unicam device /dev/media2 and ISP device /dev/media3
[0:09:27.432893147] [1997]  INFO Camera camera.cpp:841 Pipeline handler in use by another process
Camera init sequence did not complete.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 242, in init
    self._open_camera()
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 439, in _open_camera
    raise RuntimeError(f"camera.acquire() returned unexpected code: {acq_code}")
RuntimeError: camera.acquire() returned unexpected code: -16

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/11.py", line 5, in <module>
    picam2 = Picamera2()
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 249, in init
    raise RuntimeError("Camera init sequence did not complete.")
RuntimeError: Camera init sequence did not complete.
pi@raspberrypi:~ $

Do you have any idea what is the issue? what process should I follow to make sure no issues will happen?
It was working well and I was trying to capture multiple images with different exposures and the error happened out of the blue. And then, none of the example files ran at all. All have the same issue.

Thanks

**Comment by davidplowman** [comment]
Thanks for the report. It's a bit hard to guess what's happened there. It seems to be unable to open the camera, possibly because something else has ended up in a state where it's holding on to it and hasn't "died" properly. I presume you've tried a reboot to see if that clears the problem?

Obviously if you can pin down what you did to make it get into this state then we'd obviously want to look into it. Thanks.

**Comment by Msmhgn** [comment]
Thanks @davidplowman 
I reinstalled the picamera2 and RPI and the issue solved.
