### ISSUE TITLE
[BUG] importing picamera2 0.3.9

### ISSUE THREAD

**Issue by shineworld** [raspberrypi/picamera2#600]
**Describe the bug**
I've installed a fresh raspberry image from raspberry site.

Picamera installed is:
pi@raspberrypi:~/camera_server $ pip list
picamera2                        0.3.9
v4l2-python3                     0.3.1
....

Importing picamera2 there is an issue on missing V4L2_CID_MPEG_VIDEO_H264_MAX_QP

**To Reproduce**
pi@raspberrypi:~/camera_server $ python
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from picamera2 import Picamera2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/qem/.local/lib/python3.9/site-packages/picamera2/__init__.py", line 7, in <module>
    from .picamera2 import Picamera2, Preview
  File "/home/qem/.local/lib/python3.9/site-packages/picamera2/picamera2.py", line 23, in <module>
    from picamera2.encoders import Encoder, H264Encoder, MJPEGEncoder, Quality
  File "/home/qem/.local/lib/python3.9/site-packages/picamera2/encoders/__init__.py", line 2, in <module>
    from .h264_encoder import H264Encoder
  File "/home/qem/.local/lib/python3.9/site-packages/picamera2/encoders/h264_encoder.py", line 5, in <module>
    from v4l2 import (V4L2_CID_MPEG_VIDEO_H264_I_PERIOD,
ImportError: cannot import name 'V4L2_CID_MPEG_VIDEO_H264_MAX_QP' from 'v4l2' (/usr/lib/python3/dist-packages/v4l2.py)

**Hardware :**
Raspberry Pi 4

**Comment by shineworld** [comment]
Just a day after post raspberry update solved issue with a 0.3.2-1 version of v4l2:

Log started: 2023-03-04  08:09:34
(Reading database ... 97794 files and directories currently installed.)
Preparing to unpack .../0-libcamera0_0~git20230302+923f5d70-1_arm64.deb ...
Unpacking libcamera0:arm64 (0~git20230302+923f5d70-1) over (0~git20230124+9b860a66-1) ...
Preparing to unpack .../1-libcamera-apps_0~git20230301+54a781d-1_arm64.deb ...
Unpacking libcamera-apps (0~git20230301+54a781d-1) over (0~git20230125+9f08463-1) ...
Preparing to unpack .../2-libcamera-tools_0~git20230302+923f5d70-1_arm64.deb ...
Unpacking libcamera-tools (0~git20230302+923f5d70-1) over (0~git20230124+9b860a66-1) ...
Preparing to unpack .../3-python3-libcamera_0~git20230302+923f5d70-1_arm64.deb ...
Unpacking python3-libcamera (0~git20230302+923f5d70-1) over (0~git20230124+9b860a66-1) ...
Preparing to unpack .../4-python3-v4l2_0.3.2-1_all.deb ...
Unpacking python3-v4l2 (0.3.2-1) over (0.3.1-1) ...
Preparing to unpack .../5-python3-picamera2_0.3.9-1_all.deb ...
Unpacking python3-picamera2 (0.3.9-1) over (0.3.8-1) ...
Setting up python3-v4l2 (0.3.2-1) ...
Setting up libcamera0:arm64 (0~git20230302+923f5d70-1) ...
Setting up libcamera-tools (0~git20230302+923f5d70-1) ...
Setting up libcamera-apps (0~git20230301+54a781d-1) ...
Setting up python3-libcamera (0~git20230302+923f5d70-1) ...
Setting up python3-picamera2 (0.3.9-1) ...
Processing triggers for libc-bin (2.31-13+rpt2+rpi1+deb11u5) ...
Log ended: 2023-03-04  08:09:40
