### ISSUE TITLE
[BUG] No module named 'libcamera._libcamera' when running in Docker container

### ISSUE THREAD

**Issue by romerojunior** [raspberrypi/picamera2#675]
When trying to install picamera2 in a Docker image:

``` 
FROM balenalib/raspberrypi4-64-python:3.11-bullseye
WORKDIR /example
RUN apt update && apt upgrade && apt install -y python3-picamera2 --no-install-recommends
COPY . .
CMD ["python3", "example.py"]
``` 

I get the following error:

```
>>> from picamera2 import Picamera2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/picamera2/__init__.py", line 1, in <module>
    import libcamera
  File "/usr/lib/python3/dist-packages/libcamera/__init__.py", line 4, in <module>
    from ._libcamera import *
ModuleNotFoundError: No module named 'libcamera._libcamera'
```

Inside running image shell:
```
# cd /usr/lib/python3/dist-packages/libcamera
# ls -lah
total 1.2M
drwxr-xr-x 1 root root 4.0K Apr 18 16:56 .
drwxr-xr-x 1 root root 4.0K Apr 18 16:55 ..
-rw-r--r-- 1 root root  143 Mar  2 12:53 __init__.py
drwxr-xr-x 1 root root 4.0K Apr 18 19:41 __pycache__
-rw-r--r-- 1 root root 1.2M Mar  2 13:16 _libcamera.cpython-39-aarch64-linux-gnu.so
```

The import statement inside `example.py` (for what it's relevant):
```
#!/usr/bin/python3
from picamera2 import Picamera2

(...)
```

A list of packages (given the only steps executed were the ones in the Dockerfile):
```
# pip list
Package      Version
------------ -------
numpy        1.19.5
picamera2    0.3.9
pidng        4.0.9
piexif       1.1.3
Pillow       8.1.2
pip          23.0
python-prctl 1.7
setuptools   67.2.0
simplejpeg   1.6.4
v4l2-python3 0.3.2
wheel        0.40.0
```

The container runs in privileged mode, although I don't think this is any relevant given the nature of this issue (a module import).

Besides this issue, I wonder if anyone has had any success with running picamera2 from within a Docker image, and if so, what base image and steps were followed?

**Comment by romerojunior** [comment]
I managed to get it to work with:

* The following base image `balenalib/raspberry-pi-debian:latest` seems be behave better, the Dockerfile:

```
FROM balenalib/raspberry-pi-debian:latest

WORKDIR /example

RUN apt update && apt upgrade && apt install -y libcamera-dev python3-picamera2 --no-install-recommends

COPY . .

# give my example.py exposes a http endpoint:
EXPOSE 8080/tcp

CMD ["python3", "example.py"]
```

Followed by:
```
$ docker build -t my-example-image -f Dockerfile . 

$ docker run -d --network="host" \
  --name="your-own-name-here" \
  -v /dev/:/dev/ \
  --env UDEV=1 \
  --device /dev:/dev \
  --privileged \
  my-example-image
```
Note the deliberate use of `--network="host"`, which indicates that the exposed ports of my container will be binded to the host (raspberry-pi) TCP stack, which is only really relevant if you're exposing something over the network, such as an HTTP server.
