### ISSUE TITLE
[HOW-TO] Set the "Sharpness" control using Picamera2 and an HQ camera on a Pi Zero 2W

### ISSUE THREAD

**Issue by lmitcham** [raspberrypi/picamera2#810]
I am attempting to adjust the "Sharpness" value using the Picamera2 control command.  First, I simply want to see what the current value is.  I also want to adjust the "NoiseReductionMode" control value.  The code snippet that follows shows that I can print the NoiseReductionMode value, but the Sharpness is not recognized.  Picamera2 version is 0.3.12.

    CAMERA = Picamera2()
    config = CAMERA.create_video_configuration(main={"size":(2028, 1080)}, raw={"size":(4056, 3040)})
    config["transform"] = libcamera.Transform(hflip=0, vflip=1)
    CAMERA.configure(config)
    CAMERA.controls.FrameDurationLimits = (66667, 66667)    # Set to 15 fps
    CAMERA.controls.AeExposureMode = (3)
    print( "[SBV] NoiseReductionMode = " + str( CAMERA.controls.NoiseReductionMode ) ) 
    print( "[SBV] Sharpness = " + str( CAMERA.controls.Sharpness ) ) 

And here is the output on the terminal screen ...

[SBV] NoiseReductionMode = NoiseReductionModeEnum.Fast
MAIN LOOP EXCEPTION ****************************************
        An exception of type AttributeError occurred. Arguments:
("'Controls' object has no attribute 'Sharpness'",)
Traceback (most recent call last):
  File "/home/eye/dragoneyevideo2.py", line 1549, in <module>
    err = process_packet( bytes( raw_packet ) )
  File "/home/eye/dragoneyevideo2.py", line 343, in process_packet
    enforce_mode( in_packet )
  File "/home/eye/dragoneyevideo2.py", line 1013, in enforce_mode
    start_buffered_video()
  File "/home/eye/dragoneyevideo2.py", line 788, in start_buffered_video
    print( "[SBV] Sharpness = " + str( CAMERA.controls.Sharpness ) )
  File "/usr/lib/python3/dist-packages/picamera2/controls.py", line 42, in __getattribute__
    return super().__getattribute__(name)
AttributeError: 'Controls' object has no attribute 'Sharpness'

"Sharpness" is clearly listed in the same section as "NoiseReductionMode" in the Picamera2 Manual, so I am confused why one works and the other does not.

**Comment by davidplowman** [comment]
Hi, thanks for the question.

You probably need to think of the controls object as a set of new controls that you wish to apply. It doesn't tell you anything about the current values. So you you can update the "Sharpness" field (`camera.controls.Sharpness = 1.5`) and then the camera system will apply it.  Once it's been applied, the controls object will be empty again.

The current sharpness value of an image is returned in the image metadata. Does that help?
