### ISSUE TITLE
[OTHER] Cannot Allocate Memory

### ISSUE THREAD

**Issue by ajkelsey** [raspberrypi/picamera2#951]
I've upgraded to Bookworm and I am trying to get everything working again. When I try to run code that worked before I upgraded, I get this out "cannot allocate memory" error.

```
[0:09:03.443120768] [12387]  INFO Camera camera_manager.cpp:284 libcamera v0.1.0+118-563cd78e
[0:09:03.485140676] [12426]  WARN RPiSdn sdn.cpp:39 Using legacy SDN tuning - please consider moving SDN inside rpi.denoise
[0:09:03.488416753] [12426]  INFO RPI vc4.cpp:444 Registered camera /base/soc/i2c0mux/i2c@1/imx477@1a to Unicam device /dev/media4 and ISP device /dev/media1
[0:09:03.489189826] [12426]  INFO RPI pipeline_base.cpp:1142 Using configuration file '/usr/share/libcamera/pipeline/rpi/vc4/rpi_apps.yaml'
[0:09:03.496033579] [12387]  INFO Camera camera_manager.cpp:284 libcamera v0.1.0+118-563cd78e
[0:09:03.524952088] [12431]  WARN RPiSdn sdn.cpp:39 Using legacy SDN tuning - please consider moving SDN inside rpi.denoise
[0:09:03.527431590] [12431]  INFO RPI vc4.cpp:444 Registered camera /base/soc/i2c0mux/i2c@1/imx477@1a to Unicam device /dev/media4 and ISP device /dev/media1
[0:09:03.527516833] [12431]  INFO RPI pipeline_base.cpp:1142 Using configuration file '/usr/share/libcamera/pipeline/rpi/vc4/rpi_apps.yaml'
[0:09:03.538061913] [12387]  INFO Camera camera.cpp:1183 configuring streams: (0) 1920x1080-XBGR8888 (1) 2028x1080-SBGGR12_CSI2P
[0:09:03.538509719] [12431]  INFO RPI vc4.cpp:608 Sensor: /base/soc/i2c0mux/i2c@1/imx477@1a - Selected sensor format: 2028x1080-SBGGR12_1X12 - Selected unicam format: 2028x1080-pBCC
Traceback (most recent call last):
  File "/home/speedcam/python/capture.py", line 13, in <module>
    picam.configure(config)
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 1104, in configure
    self.configure_(camera_config)
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 1087, in configure_
    self.allocator.allocate(libcamera_config)
  File "/usr/lib/python3/dist-packages/picamera2/allocators/dmaallocator.py", line 43, in allocate
    fd = self.dmaHeap.alloc(f"picamera2-{i}", stream_config.frame_size)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/picamera2/dma_heap.py", line 98, in alloc
    ret = fcntl.ioctl(self.__dmaHeapHandle.get(), DMA_HEAP_IOCTL_ALLOC, alloc)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 12] Cannot allocate memory
```

```
picam = Picamera2()
config = picam.create_video_configuration(main={"size": (1920, 1080)})
picam.configure(config)
dt = datetime.now()
index = 0
while index < 15:
    milli_time = int(time.time() * 1000)
    picam.capture_file(f'images/{milli_time}.jpg')
    time.sleep(1/30)
    index += 1
```

/boot/firmware/config.txt
```
dtoverlay=imx477,cma-512
max_framebuffers=16
```

**Comment by ajkelsey** [comment]
NM. I commented out the `dtoverlay=vc4-kms-v3d` line in config.txt when I shouldn't have.
