### ISSUE TITLE
[HOW-TO] Undefined Symbol: _ZN9libcamera8controls3rpi15PispStatsOutputE

### ISSUE THREAD

**Issue by UmutDeniz26** [raspberrypi/picamera2#969]
Importing picamera2 throws me an error:
Traceback (most recent call last):
  File "/home/umut/Desktop/Raspberry_Roof_Robot/Tests/Camera/Camera.py", line 1, in <module>
    from picamera2 import PiCamera2  # Corrected import statement
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/picamera2/__init__.py", line 3, in <module>
    import libcamera
  File "/usr/lib/python3/dist-packages/libcamera/__init__.py", line 4, in <module>
    from ._libcamera import *
ImportError: /usr/lib/python3/dist-packages/libcamera/_libcamera.cpython-311-arm-linux-gnueabihf.so: undefined symbol: _ZN9libcamera8controls3rpi15PispStatsOutputE

My libcamera config:
libcamera 0.2.0

  Versions
    Sources                  : 0.2.0+49-be21f274

  Paths
    LIBCAMERA_DATA_DIR       : "/usr/local/share/libcamera"
    LIBCAMERA_SYSCONF_DIR    : "/usr/local/etc/libcamera"
    IPA_PROXY_DIR            : "/usr/local/libexec/libcamera"
    IPA_CONFIG_DIR           : "/usr/local/etc/libcamera/ipa:/usr/local/share/libcamera/ipa"
    IPA_MODULE_DIR           : "/usr/local/lib/arm-linux-gnueabihf/libcamera"

  Configuration
    IPA modules signed with  : None (modules will run isolated)
    Enabled pipelines        : imx8-isi
                               rkisp1
                               rpi/vc4
                               simple
                               uvcvideo
    Enabled IPA modules      : rkisp1
                               rpi/vc4
    Controls files           : control_ids_draft.yaml
                               control_ids_core.yaml
                               control_ids_rpi.yaml
    Properties files         : property_ids_draft.yaml
                               property_ids_core.yaml
    Hotplug support          : YES
    Tracing support          : NO
    Android support          : NO
    GStreamer support        : NO
    Python bindings          : NO
    V4L2 emulation support   : NO
    cam application          : NO
    qcam application         : NO
    lc-compliance application: NO
    Unit tests               : NO

  Subprojects
    gtest                    : YES
    libyaml                  : YES

Found ninja-1.11.1 at /usr/bin/ninja
(I used https://libcamera.org/getting-started.html)

I'm using Raspberry Pi 4:
Operating System: Raspbian GNU/Linux 12 (bookworm)
Kernel: Linux 6.1.0-rpi8-rpi-v8
Architecture: arm64

**Comment by davidplowman** [comment]
Hi, this sort of thing is normally caused by incompatible software versions. Could you check that everything is up to date with
```
sudo apt update
sudo apt full-upgrade
```
If problems persist, please try installing the latest Raspberry Pi OS from scratch. Don't touch or change any configuration parameters - any official Raspberry Pi camera should "just work".
